`${BASE_PATH}/js/tools/notes_utf8.js`,
`${BASE_PATH}/js/tools/translator.js`, 
`${BASE_PATH}/js/tools/scheduler.js`,
`${BASE_PATH}/js/tools/metronome.js`,
`${BASE_PATH}/js/tools/password.js`,
`${BASE_PATH}/js/tools/qrcode.js`,
`${BASE_PATH}/js/tools/currency.js`,
`${BASE_PATH}/js/tools/unit.js`,
`${BASE_PATH}/js/tools/text.js`,
`${BASE_PATH}/js/tools/timer.js`,
`${BASE_PATH}/js/tools/stopwatch.js`,
`${BASE_PATH}/js/tools/calculator.js`,
`${BASE_PATH}/js/tools/converter.js`,
`${BASE_PATH}/js/tools/color.js`,
`${BASE_PATH}/js/tools/styletext.js`

